[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "foundry-huff/=lib/foundry-huff/src/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
]
ffi = true
# evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
